# Generated by Django 2.2.2 on 2020-12-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='focus_city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='focus_cropId',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ManyToManyField(to='ml.Images'),
        ),
    ]
