# Generated by Django 2.2.2 on 2020-12-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20201205_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='focus_city',
            field=models.TextField(default='[]'),
        ),
    ]
