# Generated by Django 2.2.2 on 2020-12-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
        ('authorization', '0003_auto_20201205_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='menu',
            field=models.ManyToManyField(to='apis.App'),
        ),
    ]
